# Generated by Django 5.0.1 on 2024-07-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citydb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IrregularTimeSeriesFile',
        ),
    ]
